name: Nemo
description: |
  This is the Demo Racher Sidekick 
version: 0.0.1
category: Nemo
maintainer: Keerthiraja <sjkeerthi@gmail.com>
license: # The license
projectURL: https://github.com/sjkeerthi/Nemo
