Nemo:
  tty: true
  image: bitnami/apache:latest
  stdin_open: true
  volumes_from:
  - nemo-data
  labels:
    io.rancher.sidekicks: nemo-data
test-data:
  tty: true
  command:
  - cat
  image: bitnami/apache:latest
  stdin_open: true
