services:
  apache:
    image: 'bitnami/apache:latest'
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: apache-datavolume
    volumes_from:
      - apache-datavolume
apache-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - apache_data:/bitnami/apache
